const ANIME_DATA = [
    {
        id: 1,
        name: '进击的巨人',
        coverEmoji: '⚔️',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #4a0e0e 50%, #1a1a2e 100%)',
        desc: '在那个巨人支配的世界里，人类被迫建造了三道巨大的城墙来保护自己。百年的和平在一天被打破，艾伦·耶格尔亲眼目睹了母亲被巨人吞食，从此立誓要消灭所有巨人。',
        score: 9.5,
        category: ['热血', '科幻'],
        year: 2023,
        status: '完结',
        studio: 'MAPPA',
        totalEp: 87,
        updatedEp: 87,
        updateDay: 1,
        lastUpdate: '2023-11-05',
        isHot: true,
        isNew: false,
        videoSources: generateEpisodes(87)
    },
    {
        id: 2,
        name: '鬼灭之刃',
        coverEmoji: '🗡️',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #0f3460 50%, #1a1a2e 100%)',
        desc: '炭治郎一家被鬼杀害，妹妹祢豆子也变成了鬼。为了让妹妹变回人类，炭治郎加入了鬼杀队，踏上了与鬼战斗的道路。',
        score: 9.3,
        category: ['热血', '悬疑'],
        year: 2024,
        status: '连载中',
        studio: 'ufotable',
        totalEp: 55,
        updatedEp: 48,
        updateDay: 0,
        lastUpdate: '2026-08-04',
        isHot: true,
        isNew: true,
        videoSources: generateEpisodes(48)
    },
    {
        id: 3,
        name: '咒术回战',
        coverEmoji: '👁️',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #2d132c 50%, #1a1a2e 100%)',
        desc: '高中生虎杖悠仁吞下了咒物「两面宿傩的手指」，从此与最强咒灵共享一个身体。为了保护他人，他加入了东京咒术高专。',
        score: 9.2,
        category: ['热血', '悬疑'],
        year: 2024,
        status: '连载中',
        studio: 'MAPPA',
        totalEp: 47,
        updatedEp: 45,
        updateDay: 4,
        lastUpdate: '2026-08-01',
        isHot: true,
        isNew: true,
        videoSources: generateEpisodes(45)
    },
    {
        id: 4,
        name: '间谍过家家',
        coverEmoji: '🕵️',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #e94560 30%, #16213e 100%)',
        desc: '间谍「黄昏」为了执行任务，组建了一个假家庭。妻子是杀手，女儿是超能力者，三人互相隐瞒身份，开始了温馨又搞笑的日常。',
        score: 9.0,
        category: ['搞笑', '日常'],
        year: 2024,
        status: '连载中',
        studio: 'WIT STUDIO',
        totalEp: 37,
        updatedEp: 32,
        updateDay: 6,
        lastUpdate: '2026-08-03',
        isHot: true,
        isNew: true,
        videoSources: generateEpisodes(32)
    },
    {
        id: 5,
        name: '葬送的芙莉莲',
        coverEmoji: '🧝',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #533483 50%, #1a1a2e 100%)',
        desc: '勇者一行打败魔王后，精灵魔法使芙莉莲与同伴们告别。由于精灵的寿命远超人类，她决定重新踏上旅程，了解人类，完成与故人的约定。',
        score: 9.6,
        category: ['热血', '科幻'],
        year: 2024,
        status: '完结',
        studio: 'MADHOUSE',
        totalEp: 28,
        updatedEp: 28,
        updateDay: 5,
        lastUpdate: '2024-03-30',
        isHot: true,
        isNew: false,
        videoSources: generateEpisodes(28)
    },
    {
        id: 6,
        name: '我推的孩子',
        coverEmoji: '⭐',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #ff6b85 50%, #16213e 100%)',
        desc: '一位医生因事故转生为他推的偶像的孩子。在演艺圈的黑暗中，他决定保护母亲和妹妹，并对导致母亲死亡的人复仇。',
        score: 9.1,
        category: ['悬疑', '恋爱'],
        year: 2024,
        status: '连载中',
        studio: '动画工房',
        totalEp: 24,
        updatedEp: 20,
        updateDay: 3,
        lastUpdate: '2026-07-31',
        isHot: true,
        isNew: true,
        videoSources: generateEpisodes(20)
    },
    {
        id: 7,
        name: '排球少年',
        coverEmoji: '🏐',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #f39c12 50%, #1a1a2e 100%)',
        desc: '身高不足的日向翔阳，凭借惊人的弹跳力和毅力，与天才二传手影山飞雄一起，带领乌野高中排球部向全国大赛进军。',
        score: 9.4,
        category: ['热血', '日常'],
        year: 2020,
        status: '完结',
        studio: 'Production I.G',
        totalEp: 85,
        updatedEp: 85,
        updateDay: 2,
        lastUpdate: '2020-12-20',
        isHot: true,
        isNew: false,
        videoSources: generateEpisodes(85)
    },
    {
        id: 8,
        name: '辉夜大小姐想让我告白',
        coverEmoji: '💕',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #e94560 50%, #16213e 100%)',
        desc: '学生会长白银御行和副会长四宫辉夜互相喜欢，但都太傲娇不愿意先告白。一场「如何让对方先告白」的恋爱头脑战就此展开。',
        score: 9.0,
        category: ['恋爱', '搞笑'],
        year: 2022,
        status: '完结',
        studio: 'A-1 Pictures',
        totalEp: 37,
        updatedEp: 37,
        updateDay: 5,
        lastUpdate: '2022-06-25',
        isHot: false,
        isNew: false,
        videoSources: generateEpisodes(37)
    },
    {
        id: 9,
        name: '蓝色监狱',
        coverEmoji: '⚽',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #0f3460 50%, #2a2a4a 100%)',
        desc: '日本足球在世界杯惨败后，为了培养世界级的前锋，300名高中生被聚集到「蓝色监狱」，只有一个人能站到顶点。',
        score: 8.8,
        category: ['热血', '日常'],
        year: 2024,
        status: '连载中',
        studio: '8bit',
        totalEp: 36,
        updatedEp: 30,
        updateDay: 6,
        lastUpdate: '2026-08-03',
        isHot: true,
        isNew: true,
        videoSources: generateEpisodes(30)
    },
    {
        id: 10,
        name: '药屋少女的呢喃',
        coverEmoji: '🌿',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #27ae60 50%, #1a1a2e 100%)',
        desc: '在花街当药师的猫猫被拐入后宫，她凭借药学知识破解了一个又一个谜团，却也被卷入了宫廷的权力斗争中。',
        score: 9.2,
        category: ['悬疑', '恋爱'],
        year: 2024,
        status: '连载中',
        studio: 'OLM',
        totalEp: 30,
        updatedEp: 26,
        updateDay: 0,
        lastUpdate: '2026-08-04',
        isHot: true,
        isNew: true,
        videoSources: generateEpisodes(26)
    },
    {
        id: 11,
        name: '迷宫饭',
        coverEmoji: '🍖',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #d68910 50%, #1a1a2e 100%)',
        desc: '莱欧斯的妹妹被龙吃掉了，为了救妹妹，他决定一边在迷宫里做「魔物料理」一边冒险。一部魔物美食奇幻剧。',
        score: 9.1,
        category: ['搞笑', '日常'],
        year: 2024,
        status: '连载中',
        studio: 'TRIGGER',
        totalEp: 24,
        updatedEp: 22,
        updateDay: 4,
        lastUpdate: '2026-08-01',
        isHot: false,
        isNew: true,
        videoSources: generateEpisodes(22)
    },
    {
        id: 12,
        name: '无职转生',
        coverEmoji: '🧙',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #3498db 50%, #1a1a2e 100%)',
        desc: '34岁的尼特族转生到异世界，带着前世的记忆和遗憾，决定这一次要认真生活。鲁迪乌斯的冒险就此开始。',
        score: 9.3,
        category: ['热血', '科幻'],
        year: 2024,
        status: '连载中',
        studio: 'Studio Bind',
        totalEp: 45,
        updatedEp: 42,
        updateDay: 1,
        lastUpdate: '2026-07-29',
        isHot: true,
        isNew: true,
        videoSources: generateEpisodes(42)
    },
    {
        id: 13,
        name: '四月是你的谎言',
        coverEmoji: '🎹',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #e94560 50%, #2c3e50 100%)',
        desc: '钢琴天才有马公生因母亲去世无法再弹琴，直到他遇见了小提琴手宫园薰，两人用音乐交织出一段青春的恋曲。',
        score: 9.4,
        category: ['恋爱', '日常'],
        year: 2015,
        status: '完结',
        studio: 'A-1 Pictures',
        totalEp: 22,
        updatedEp: 22,
        updateDay: 3,
        lastUpdate: '2015-03-20',
        isHot: false,
        isNew: false,
        videoSources: generateEpisodes(22)
    },
    {
        id: 14,
        name: '孤独摇滚',
        coverEmoji: '🎸',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #e94560 50%, #f39c12 100%)',
        desc: '社恐少女后藤一里渴望组乐队，意外加入了「纽带乐队」。她的摇滚青春与成长故事就此开始。',
        score: 9.2,
        category: ['搞笑', '日常'],
        year: 2023,
        status: '完结',
        studio: 'CloverWorks',
        totalEp: 12,
        updatedEp: 12,
        updateDay: 6,
        lastUpdate: '2023-12-24',
        isHot: true,
        isNew: false,
        videoSources: generateEpisodes(12)
    },
    {
        id: 15,
        name: '赛博朋克：边缘行者',
        coverEmoji: '🤖',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #e94560 40%, #533483 100%)',
        desc: '在未来的夜之城，少年大卫因一次意外安装了军事级别的改造装置，从此踏上了成为边缘行者的危险道路。',
        score: 9.4,
        category: ['热血', '科幻'],
        year: 2022,
        status: '完结',
        studio: 'TRIGGER',
        totalEp: 10,
        updatedEp: 10,
        updateDay: 2,
        lastUpdate: '2022-09-21',
        isHot: true,
        isNew: false,
        videoSources: generateEpisodes(10)
    },
    {
        id: 16,
        name: '天国大魔境',
        coverEmoji: '🌅',
        cover: '',
        banner: 'linear-gradient(135deg, #1a1a2e 0%, #27ae60 50%, #0f3460 100%)',
        desc: '大灾难15年后，少年真流带着神秘指令踏上旅程，寻找「天国」。平行的故事线中，一群孩子生活在被围墙包围的学园里。',
        score: 9.0,
        category: ['悬疑', '科幻'],
        year: 2023,
        status: '完结',
        studio: 'Production I.G',
        totalEp: 13,
        updatedEp: 13,
        updateDay: 4,
        lastUpdate: '2023-06-24',
        isHot: false,
        isNew: false,
        videoSources: generateEpisodes(13)
    }
];

function generateEpisodes(count) {
    const episodes = [];
    // 公共测试视频源（仅用于演示，国内可能无法访问）
    // 替换为您自己的视频源 URL，支持 .mp4 / .m3u8 / .webm
    const samples = [
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
    ];
    for (let i = 1; i <= count; i++) {
        episodes.push({
            ep: i,
            title: i === 1 ? '第1话 开始的地方' : `第${i}话`,
            url: samples[i % samples.length],
            isNew: i === count,
            isDemo: true  // 标记为演示视频，会显示配置引导
        });
    }
    return episodes;
}

const WEEK_DAYS = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];
